### ISSUE TITLE
Move to java-docs-samples under cloud-storage folder

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/cloud-storage-docs-xml-api-examples#1]
Hi @marcgel 

We're moving all docs samples to github in a central location based on language. If you could move this that would be great. I can submit the pull request but if you could then update the docs and let me know when I can delete this that would be great!

**Comment by tswast** [comment]
Added deprecation notice in https://github.com/GoogleCloudPlatform/cloud-storage-docs-xml-api-examples/commit/1d9ad049daa52c7bb3bc0529fb29cbbf17d37d98
